
  
//  List<LanguageOption> languageOptions = [ 
//   //
//   LanguageOption('af', 'Afrikaans'),
//   LanguageOption('sq', 'Albanian'),
//   LanguageOption('am', 'Amharic'),
//   LanguageOption('ar', 'Arabic'),
//   LanguageOption('hy', 'Armenian'),
//   LanguageOption('az', 'Azerbaijani'),
//   LanguageOption('eu', 'Basque'),
//   LanguageOption('be', 'Belarusian'),
//   LanguageOption('bn', 'Bengali'),
//   LanguageOption('bs', 'Bosnian'),
//   LanguageOption('bg', 'Bulgarian'),
//   LanguageOption('ca', 'Catalan'),
//   LanguageOption('ceb', 'Cebuano'),
//   LanguageOption('ny', 'Chichewa'),
//   // LanguageOption('zh', 'Chinese (Simplified)'),
//   // LanguageOption('zh-TW', 'Chinese (Traditional)'),
//   LanguageOption('co', 'Corsican'),
//   LanguageOption('hr', 'Croatian'),
//   LanguageOption('cs', 'Czech'),
//   LanguageOption('da', 'Danish'),
//   LanguageOption('nl', 'Dutch'),
//   LanguageOption('en', 'English'),
//   LanguageOption('eo', 'Esperanto'),
//   LanguageOption('et', 'Estonian'),
//   LanguageOption('tl', 'Filipino'),
//   LanguageOption('fi', 'Finnish'),
//   LanguageOption('fr', 'French'),
//   LanguageOption('fy', 'Frisian'),
//   LanguageOption('gl', 'Galician'),
//   LanguageOption('ka', 'Georgian'),
//   LanguageOption('de', 'German'),
//   LanguageOption('el', 'Greek'),
//   LanguageOption('gu', 'Gujarati'),
//   LanguageOption('ht', 'Haitian Creole'),
//   LanguageOption('ha', 'Hausa'),
//   LanguageOption('haw', 'Hawaiian'),
//   LanguageOption('iw', 'Hebrew'),
//   LanguageOption('hi', 'Hindi'),
//   LanguageOption('hmn', 'Hmong'),
//   LanguageOption('hu', 'Hungarian'),
//   LanguageOption('is', 'Icelandic'),
//   LanguageOption('ig', 'Igbo'),
//   LanguageOption('id', 'Indonesian'),
//   LanguageOption('ga', 'Irish'),
//   LanguageOption('it', 'Italian'),
//   LanguageOption('ja', 'Japanese'),
//   LanguageOption('jw', 'Javanese'),
//   LanguageOption('kn', 'Kannada'),
//   LanguageOption('kk', 'Kazakh'),
//   LanguageOption('km', 'Khmer'),
//   LanguageOption('ko', 'Korean'),
//   LanguageOption('ku', 'Kurdish'),
//   LanguageOption('ky', 'Kyrgyz'),
//   LanguageOption('lo', 'Lao'),
//   LanguageOption('la', 'Latin'),
//   LanguageOption('lv', 'Latvian'),
//   LanguageOption('lt', 'Lithuanian'),
//   LanguageOption('lb', 'Luxembourgish'),
//   LanguageOption('mk', 'Macedonian'),
//   LanguageOption('mg', 'Malagasy'),
//   LanguageOption('ms', 'Malay'),
//   LanguageOption('ml', 'Malayalam'),
//   LanguageOption('mt', 'Maltese'),
//   LanguageOption('mi', 'Maori'),
//   LanguageOption('mr', 'Marathi'),
//   LanguageOption('mn', 'Mongolian'),
//   LanguageOption('my', 'Burmese'),
//   LanguageOption('ne', 'Nepali'),
//   LanguageOption('no', 'Norwegian'),
//   LanguageOption('ps', 'Pashto'),
//   LanguageOption('fa', 'Persian'),
//   LanguageOption('pl', 'Polish'),
//   LanguageOption('pt', 'Portuguese'),
//   LanguageOption('pa', 'Punjabi'),
//   LanguageOption('ro', 'Romanian'),
//   LanguageOption('ru', 'Russian'),
//   LanguageOption('sm', 'Samoan'),
//   LanguageOption('gd', 'Scots Gaelic'),
//   LanguageOption('sr', 'Serbian'),
//   LanguageOption('st', 'Sesotho'),
//   LanguageOption('sn', 'Shona'),
//   LanguageOption('sd', 'Sindhi'),
//   LanguageOption('si', 'Sinhala'),
//   LanguageOption('sk', 'Slovak'),
//   LanguageOption('sl', 'Slovenian'),
//   LanguageOption('so', 'Somali'),
//   LanguageOption('es', 'Spanish'),
//   LanguageOption('su', 'Sundanese'),
//   LanguageOption('sw', 'Swahili'),
//   LanguageOption('sv', 'Swedish'),
//   LanguageOption('tg', 'Tajik'),
//   LanguageOption('ta', 'Tamil'),
//   LanguageOption('tt', 'Tatar'),
//   LanguageOption('te', 'Telugu'),
//   LanguageOption('th', 'Thai'),
//   LanguageOption('tr', 'Turkish'),
//   LanguageOption('tk', 'Turkmen'),
//   LanguageOption('uk', 'Ukrainian'),
//   LanguageOption('ur', 'Urdu'),
//   LanguageOption('ug', 'Uyghur'),
//   LanguageOption('uz', 'Uzbek'),
//   LanguageOption('vi', 'Vietnamese'),
//   LanguageOption('cy', 'Welsh'),
//   LanguageOption('xh', 'Xhosa'),
//   LanguageOption('yi', 'Yiddish'),
//   LanguageOption('yo', 'Yoruba'),
//   LanguageOption('zu', 'Zulu'),
//   // Add more language options here
// ];



 


// class LanguageOption {
//   final String languageCode;
//   final String languageName;

//   LanguageOption(this.languageCode, this.languageName);
// }